const express = require('express');
const router = express.Router();
const nodemailer = require('nodemailer');
const Message = require('../models/Message');
const Setting = require('../models/Setting');
const { protect, admin } = require('../middleware/authMiddleware');

// Setup Nodemailer Transporter
const getTransporter = () => {
  if (process.env.SMTP_USER && process.env.SMTP_PASS) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT) || 587,
      secure: process.env.SMTP_SECURE === 'true', // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return null;
};

// @desc    Submit contact message
// @route   POST /api/contact
// @access  Public
router.post('/', async (req, res) => {
  try {
    const { name, email, subject, message } = req.body;

    if (!name || !email || !subject || !message) {
      return res.status(400).json({ message: 'All fields are required' });
    }

    const newMessage = await Message.create({ name, email, subject, message });

    // Fetch dynamic store name and contact email for notifications
    const settings = await Setting.findOne();
    const storeName = settings?.storeName || 'KGN Accessories';
    const adminEmail = settings?.contactEmail || 'support@kgnaccessories.com';

    // Send Email to Admin if SMTP configured
    const transporter = getTransporter();
    if (transporter) {
      const mailOptions = {
        from: `"${name}" <${email}>`,
        to: adminEmail,
        subject: `New Contact Submission: ${subject}`,
        html: `
          <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
            <h2 style="color: #4f46e5; border-bottom: 2px solid #eaeaea; padding-bottom: 10px;">New Store Inquiry</h2>
            <p><strong>From:</strong> ${name} (&lt;${email}&gt;)</p>
            <p><strong>Subject:</strong> ${subject}</p>
            <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #4f46e5; margin-top: 15px; border-radius: 4px;">
              <p style="white-space: pre-wrap; line-height: 1.6; margin: 0;">${message}</p>
            </div>
            <p style="font-size: 11px; color: #888; margin-top: 25px; border-top: 1px solid #eee; padding-top: 10px;">
              This notification was generated by ${storeName} database mail system.
            </p>
          </div>
        `,
      };
      await transporter.sendMail(mailOptions);
    }

    res.status(201).json({ message: 'Message sent successfully!', data: newMessage });
  } catch (error) {
    console.error('Contact Submission Error:', error);
    res.status(500).json({ message: 'Server Error submitting contact message' });
  }
});

// @desc    Get logged in user's contact messages
// @route   GET /api/contact/my
// @access  Private
router.get('/my', protect, async (req, res) => {
  try {
    const messages = await Message.find({ email: req.user.email }).sort({ createdAt: -1 });
    res.json(messages);
  } catch (error) {
    res.status(500).json({ message: 'Server Error fetching user inquiries' });
  }
});

// @desc    Get all messages (Admin only)
// @route   GET /api/contact
// @access  Private/Admin
router.get('/', protect, admin, async (req, res) => {
  try {
    const messages = await Message.find().sort({ createdAt: -1 });
    res.json(messages);
  } catch (error) {
    res.status(500).json({ message: 'Server Error fetching messages' });
  }
});

// @desc    Mark message as read/unread (Admin only)
// @route   PUT /api/contact/:id/read
// @access  Private/Admin
router.put('/:id/read', protect, admin, async (req, res) => {
  try {
    const message = await Message.findById(req.params.id);
    if (!message) {
      return res.status(404).json({ message: 'Message not found' });
    }

    message.isRead = req.body.isRead !== undefined ? req.body.isRead : !message.isRead;
    const updated = await message.save();
    res.json(updated);
  } catch (error) {
    res.status(500).json({ message: 'Server Error marking message' });
  }
});

// @desc    Reply to a contact message via email (Admin only)
// @route   POST /api/contact/:id/reply
// @access  Private/Admin
router.post('/:id/reply', protect, admin, async (req, res) => {
  try {
    const { replyText } = req.body;
    if (!replyText) {
      return res.status(400).json({ message: 'Reply content is required' });
    }

    const message = await Message.findById(req.params.id);
    if (!message) {
      return res.status(404).json({ message: 'Inquiry not found' });
    }

    const settings = await Setting.findOne();
    const storeName = settings?.storeName || 'KGN Accessories';
    const adminEmail = settings?.contactEmail || 'support@kgnaccessories.com';

    // Send email to user
    const transporter = getTransporter();
    let emailSent = false;
    let mailErrorMsg = "";

    if (transporter) {
      try {
        const mailOptions = {
          from: `"${storeName}" <${adminEmail}>`,
          to: message.email,
          subject: `Re: ${message.subject}`,
          html: `
            <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
              <p>Hi ${message.name},</p>
              <p>Thank you for contacting us. Here is the response to your inquiry regarding <strong>"${message.subject}"</strong>:</p>
              <div style="background-color: #f1f5f9; padding: 15px; border-left: 4px solid #3b82f6; margin: 15px 0; border-radius: 4px; line-height: 1.6;">
                <p style="white-space: pre-wrap; margin: 0;">${replyText}</p>
              </div>
              <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
              <p style="font-size: 12px; color: #666;">Best Regards,<br><strong>Customer Support Team</strong><br>${storeName}</p>
              <div style="margin-top: 25px; font-size: 11px; color: #999; border-top: 1px solid #f0f0f0; padding-top: 10px;">
                <p><strong>Your original message:</strong></p>
                <blockquote style="margin: 0; padding-left: 10px; border-left: 2px solid #ccc; font-style: italic;">
                  ${message.message}
                </blockquote>
              </div>
            </div>
          `,
        };
        await transporter.sendMail(mailOptions);
        emailSent = true;
      } catch (mailError) {
        console.error('Mail sending failed:', mailError);
        mailErrorMsg = " (SMTP mail server failed to dispatch)";
      }
    }

    message.reply = replyText;
    message.repliedAt = Date.now();
    message.isRead = true; // reply auto-marks it read
    await message.save();

    res.json({
      message: emailSent
        ? 'Reply sent and logged successfully!'
        : `Reply saved in database!${mailErrorMsg || ' (Email skipped: SMTP credentials not set in .env)'}`,
      data: message
    });
  } catch (error) {
    console.error('Email Reply Error:', error);
    res.status(500).json({ message: error.message || 'Server Error sending reply' });
  }
});

// @desc    Delete contact message (Admin only)
// @route   DELETE /api/contact/:id
// @access  Private/Admin
router.delete('/:id', protect, admin, async (req, res) => {
  try {
    const message = await Message.findById(req.params.id);
    if (!message) {
      return res.status(404).json({ message: 'Message not found' });
    }
    await message.deleteOne();
    res.json({ message: 'Message deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Server Error deleting message' });
  }
});

module.exports = router;
